// <auto-generated />
using System;
using OwlCTF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OwlCTF.Data.Migrations
{
    [DbContext(typeof(InstanceDbContext))]
    partial class InstanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OwlCTF.Data.ChallengeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActiveLeaseKey")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("HostPort")
                        .HasColumnType("int");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveLeaseKey")
                        .IsUnique();

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("ChallengeInstances", (string)null);
                });

            modelBuilder.Entity("OwlCTF.Data.ChallengeInstanceConfig", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ContainerPort")
                        .HasColumnType("int");

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FlagEnvironmentVariable")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("MaxRenewals")
                        .HasColumnType("int");

                    b.Property<long>("MemoryBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("NanoCpus")
                        .HasColumnType("bigint");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ChallengeId");

                    b.ToTable("ChallengeInstanceConfigs", (string)null);
                });

            modelBuilder.Entity("OwlCTF.Data.CheatIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AdminNotified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("AdminNotifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("AutoBanApplied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ManualBanAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ManualBanByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OwningChallengeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OwningTeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubmittedChallengeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubmittingTeamId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SubmittingUserId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("SubmissionAttemptId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SubmissionAttemptId")
                        .IsUnique();

                    b.ToTable("CheatIncidents", (string)null);
                });

            modelBuilder.Entity("OwlCTF.Data.InstanceCapacityLock", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("InstanceCapacityLocks", (string)null);
                });

            modelBuilder.Entity("OwlCTF.Data.InstanceFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChallengeInstanceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlagHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FlagHash")
                        .IsUnique();

                    b.ToTable("InstanceFlags", (string)null);
                });

            modelBuilder.Entity("OwlCTF.Data.TeamMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId");

                    b.ToTable("TeamMembers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OwlCTF.Data.TeamSecurityState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FlaggedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Teams", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
